name: Deploy static site
on: [workflow_dispatch]
jobs: 
  run-main-exporter-php:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: intl
        tools: composer:v2
    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setup env variables
        env:
          SOURCE_S3_BUCKET: ${{ secrets.SOURCE_S3_BUCKET }}
          OUTPUT_S3_BUCKET: ${{ secrets.OUTPUT_S3_BUCKET }}
          #OUTPUT_S3_ID: ${{ secrets.OUTPUT_S3_ID }}
          #OUTPUT_S3_KEY: ${{ secrets.OUTPUT_S3_KEY }}
      run: echo -e  'SOURCE_S3_BUCKET=${{ secrets.SOURCE_S3_BUCKET }}\nOUTPUT_S3_BUCKET=${{ secrets.OUTPUT_S3_BUCKET }}' > $GITHUB_WORKSPACE/.env
    - name: Run script
      run: php run.php